[[clients]]
handle = "Aashir"
port = [ 5008, 6000,]
whoisport = 4000
autoreply = "in einer Stunde da"
away = false
imagepath = "./images/aashir"

[[clients]]
handle = "Bratli"
port = [ 5004, 6000,]
whoisport = 4000
autoreply = "Bin AFK."
away = false
imagepath = "./images/bratli"

[[clients]]
handle = "Jalal"
port = [ 5005, 6000,]
whoisport = 4000
autoreply = "Bin in 10 Minuten wieder da."
away = false
imagepath = "./images/jalal"
